spring:
    data:
      mongodb:
        uri: mongodb+srv://${DB_USER:admin}:${DB_PASSWORD}@webfluxcoursecluster.yww3hos.mongodb.net/${DB_NAME:webflux-c}?retryWrites=true&w=majority
        auto-index-creation: true
    application:
      name: webflux-course